### ISSUE TITLE
Player deflecting

### ISSUE THREAD

**Issue by oliver-leung** [oliver-leung/night-bite#21]
Players should have the ability to press a button to block attacks. This would entail that they would be unable to be damaged/knocked back by these attacks.

I'm not sure whether we're gonna extend this to allow them to push through crowds while blocking. or if this would reduce the player's speed; it'll probably be clarified at the full team meeting.

**Comment by leewang-codes** [comment]
The blocking action will instead be a reflecting action, similar to the wrench in Nuclear Throne. It will be controlled with a mouse click. It should push NPCs away and reflect firecrackers.
