### ISSUE TITLE
Enemy movement

### ISSUE THREAD

**Issue by oliver-leung** [oliver-leung/night-bite#47]
Some players think that enemies move unnaturally and not physics-y. Change AI pathfinding so that forces are more naturally applied to the enemies when moving.

**Comment by attilusleung** [comment]
- Replan when reach end of path
- Replan when respawn
- Replan when knocked back from collision (check distance to node? should be < 2)

**Comment by attilusleung** [comment]
also walk diagonally

**Comment by attilusleung** [comment]
also separate dynamic map for each enemy
