### ISSUE TITLE
Rework firework detonation

### ISSUE THREAD

**Issue by oliver-leung** [oliver-leung/night-bite#49]
Firecracker detonation time should be decreased to make them pose more of a threat to the player. (or was it increased? I can't remember)

**Comment by leewang-codes** [comment]
The sound effects should be changed to be more accurate to the explosion timing. Sound effects should include flying, fizzle, and detonation.

**Comment by leewang-codes** [comment]
Firecrackers should only explode for a split second - not continuously.

**Comment by leewang-codes** [comment]
A light should show firecracker blast radius.

**Comment by leewang-codes** [comment]
Implemented with #81 and #78
